### ISSUE TITLE
Text display issue on Android in French

### ISSUE THREAD

**Issue by michamos** [alexiri/opendays2019-feedback#1]
**Describe the bug**
Some unicode text characters are not displayed correctly on Android 9.0. I noticed this for `’` (or whatever other specific character is used for apostrophes) in French.

**To Reproduce**
1. Go to any page with text in French
2. See error

**Expected behavior**
All characters are displayed properly.

**Screenshots**
![Screenshot_20190801-094757](https://user-images.githubusercontent.com/2895793/62275169-aaa00b00-b441-11e9-85e2-7b3c65e9bb82.png)

**Smartphone (please complete the following information):**
 - Device: Motorola G7
 - OS: Android 9.0

**Comment by alexiri** [comment]
Thanks, fixed.
